package org.hivedb.util;

import java.util.Collection;
import java.util.Collections;
import java.util.Map;

import org.hivedb.Hive;
import org.hivedb.meta.PrimaryIndexIdentifiable;
import org.hivedb.meta.ResourceIdentifiable;
import org.hivedb.meta.SecondaryIndexIdentifiable;
import org.hivedb.util.functional.Filter;
import org.hivedb.util.functional.Generate;
import org.hivedb.util.functional.Generator;
import org.hivedb.util.functional.NumberIterator;
import org.hivedb.util.functional.Predicate;
import org.hivedb.util.functional.RingIteratorable;
import org.hivedb.util.functional.Transform;
import org.hivedb.util.functional.Unary;
import org.hivedb.util.scenarioBuilder.HiveScenarioConfig;

public class GenerateHiveIndexKeys {
	
	private Persister persister = new PersisterImpl();
	private int primaryInstanceCount;
	private int resourceInstanceCount;
	public GenerateHiveIndexKeys(Persister persister, int primaryIndexInstanceCount, int resourceInstanceCount)
	{
		this.persister = persister;
		this.primaryInstanceCount = primaryIndexInstanceCount;
		this.resourceInstanceCount = resourceInstanceCount;
	}
	
	/**
	 *  Given a Hive and HiveScenarioConfig create and persist a collection of PrimaryIndexIdentifiable instances for eatch PrimaryIndexIdentifiable class.
	 *  The classes and number of instances are defined in the hiveScenarioConfig.
	 *  
	 *  This method is used createSecondaryIndexIdentifiableInstances(), so it's not necessary to call this directly if you are generating 
	 *  
	 * @param hive
	 * @param hiveScenarioConfig
	 * @return
	 */
	public Map<PrimaryIndexIdentifiable, Collection<PrimaryIndexIdentifiable>> 
		createPrimaryIndexInstances(final Hive hive, final HiveScenarioConfig hiveScenarioConfig)
	{	
		return Transform.toMap(
			new Transform.IdentityFunction<PrimaryIndexIdentifiable>(),
			new Unary<PrimaryIndexIdentifiable, Collection<PrimaryIndexIdentifiable>>() {
				public Collection<PrimaryIndexIdentifiable> f(final PrimaryIndexIdentifiable primaryIndexIdentifiablePrototype) {		
					return Generate.create(new Generator<PrimaryIndexIdentifiable>() { 
						public PrimaryIndexIdentifiable f() {
							try {
								final PrimaryIndexIdentifiable newPrimaryIndexIdentifiable = primaryIndexIdentifiablePrototype.generate();
								persister.persistPrimaryIndexIdentifiable(hive, newPrimaryIndexIdentifiable);						
								return newPrimaryIndexIdentifiable;
							} catch (Exception e) { throw new RuntimeException(e); }
						}},
						new NumberIterator(primaryInstanceCount));
				}
			},
			Collections.singleton(hiveScenarioConfig.getPrimaryIndexIdentifiable()));
	}	
	

	/**
	 *  Create a collection of ResourceIdentifiableInstances for each ResourceIdentifiable class. Each ResourceIdentifiableInstance refers to
	 *  one of the PrimaryIndexInstances generated by 
	 * @param hive
	 * @param hiveScenarioConfig
	 * @param primaryIndexInstanceMap
	 * @return
	 */
	public Map<PrimaryIndexIdentifiable, Map<ResourceIdentifiable, Collection<ResourceIdentifiable>>>
		createSecondaryIndexInstances(
			final Hive hive,
			final HiveScenarioConfig hiveScenarioConfig,
			final Map<PrimaryIndexIdentifiable, Collection<PrimaryIndexIdentifiable>> primaryIndexInstanceMap)
	{
		return Transform.toMap(
			new Transform.IdentityFunction<PrimaryIndexIdentifiable>(),
			makeMapperToResourceIdentifiableMap(hive, hiveScenarioConfig, primaryIndexInstanceMap),
			Collections.singleton(hiveScenarioConfig.getPrimaryIndexIdentifiable()));
	}
	
	private Unary<PrimaryIndexIdentifiable, Map<ResourceIdentifiable, Collection<ResourceIdentifiable>>>
		makeMapperToResourceIdentifiableMap(
				final Hive hive,
				final HiveScenarioConfig hiveScenarioConfig,
				final Map<PrimaryIndexIdentifiable, Collection<PrimaryIndexIdentifiable>> primaryIndexInstanceMap) {
		
		// Make a RingIterable that iterates over the primary instancees,
		// for countPerSecondaryIndex, but limit it it to the number of primaryInstances to prevent duplicate primary keys
		// when the secondaryInstance is the same as the primaryInstance
		
		return new Unary<PrimaryIndexIdentifiable, Map<ResourceIdentifiable, Collection<ResourceIdentifiable>>>() {				
			public Map<ResourceIdentifiable, Collection<ResourceIdentifiable>> 
				f(PrimaryIndexIdentifiable primaryIndexIdentifiablePrototype) {	
				
				Collection<PrimaryIndexIdentifiable> primaryIndexIdentifiables = primaryIndexInstanceMap.get(primaryIndexIdentifiablePrototype);
				String partitionDimensionName = primaryIndexIdentifiablePrototype.getPartitionDimensionName();
					
				return Transform.toMap(
					new Transform.IdentityFunction<ResourceIdentifiable>(),
					makeResourceToSecondaryIndexIdentifiableGrower(hive, hiveScenarioConfig, primaryIndexIdentifiables),
					filterByPartitionDimensionName(primaryIndexIdentifiablePrototype.getResourceIdentifiables(), primaryIndexIdentifiablePrototype, partitionDimensionName)
				);						
			}
			
			private Collection<ResourceIdentifiable> filterByPartitionDimensionName(
					final Collection<ResourceIdentifiable> resourceIdentifiabes,
					final PrimaryIndexIdentifiable primaryIndexIdentifiable,
					final String partitionDimensionName)
			{
				return Filter.grep(new Predicate<ResourceIdentifiable>() {
				public boolean f(ResourceIdentifiable resourceIdentifiableClass) {
					return primaryIndexIdentifiable.getPartitionDimensionName()
						.equals(partitionDimensionName);
				}}, resourceIdentifiabes);
			}
		};
	}
	
	private Unary<ResourceIdentifiable, Collection<ResourceIdentifiable>>
		makeResourceToSecondaryIndexIdentifiableGrower(
			final Hive hive,
			final HiveScenarioConfig hiveScenarioConfig,
			final Collection<PrimaryIndexIdentifiable> primaryIndexIdentifiables) {
			
		return new Unary<ResourceIdentifiable, Collection<ResourceIdentifiable>>() {
			public Collection<ResourceIdentifiable>
				f(final ResourceIdentifiable resourceIdentifiablePrototype) {	
				
				// We need to behave differently if our ResourceIdentifiable class equals its PrimaryIndexIdentifiable class.
				// If it does we have to limit the number of SecondaryIndexIdentifiable instances that we generate
				// to the number of PrimaryIndexIdentifiable instances that we have, since it's a 1-to-1 relationship.
				// Also, if it's not the sameClass then we want to construct the ResourceIdentifiable with a reference
				// to it's PrimaryIndexIdentifiable instance.
				final boolean sameClass = (resourceIdentifiablePrototype.equals(resourceIdentifiablePrototype.getPrimaryIndexIdentifiable().getClass()));
				final Iterable<PrimaryIndexIdentifiable> primaryPartitionIndexInstanceIterable = new RingIteratorable<PrimaryIndexIdentifiable>(
					primaryIndexIdentifiables,
					sameClass
						? Math.min(resourceInstanceCount, primaryIndexIdentifiables.size()) // limit it
						: resourceInstanceCount); 	// follow our configuration preference		
				
				return Transform.map(
					makeResourceIdentifiableGrower(hive, hiveScenarioConfig, resourceIdentifiablePrototype, sameClass),
					primaryPartitionIndexInstanceIterable);	
		}};	
	}
		
	private Unary<PrimaryIndexIdentifiable, ResourceIdentifiable> makeResourceIdentifiableGrower(final Hive hive, final HiveScenarioConfig hiveScenarioConfig, final ResourceIdentifiable resourceIdentifiablePrototype, final boolean sameClass) {
		return new Unary<PrimaryIndexIdentifiable, ResourceIdentifiable>() { 
			public ResourceIdentifiable f(PrimaryIndexIdentifiable primaryIndexIdentifiable) {
				ResourceIdentifiable resourceIdentifiable = resourceIdentifiablePrototype.generate(primaryIndexIdentifiable);
				resourceIdentifiable = persister.persistResourceIdentifiableInstance(hive, resourceIdentifiable);
				for (SecondaryIndexIdentifiable secondaryIndexIdentifiable : resourceIdentifiable.getSecondaryIndexIdentifiables()) {
					persistSecondaryIndexIdentifiable(hive, secondaryIndexIdentifiable);
				}
				return resourceIdentifiable;
		}

		private void persistSecondaryIndexIdentifiable(final Hive hive, SecondaryIndexIdentifiable secondaryIndexIdentifiable) {
			try {
				persister.persistSecondaryIndexIdentifiableInstance(hive, secondaryIndexIdentifiable);
			} catch (Exception e) {
				throw new RuntimeException(e);
			}
		}};
	}	
}
